### ISSUE TITLE
Error running searoute

### ISSUE THREAD

**Issue by damilare-osunleke** [genthalili/searoute-py#16]
Running the sample code (shown below) in the readme returns an error: "ImportError: scikit-learn must be installed to search an unprojected graph"

import searoute as sr
origin = [0.3515625, 50.064191736659104]
destination = [117.42187500000001, 39.36827914916014]
route = sr.searoute(origin, destination)

Note:I have scikit-learn installed

**Comment by damilare-osunleke** [comment]
issue resolved

**Comment by bmm23** [comment]
I'm having the same issue right now as well

**Comment by genthalili** [comment]
Closing, feel free to open a new issues if this occurs
