### ISSUE TITLE
Update the marnet_densified_v2.geojson for both Taiwan and Japan

### ISSUE THREAD

**Issue by LinYouMin** [genthalili/searoute-py#18]
Dear Sir,

To make the route around Taiwan and Japan more reasonable, I've updated the geojson file with added coastal lines.
Did some extensive test between the ports of Taiwan and Japan.
See attached the revised Json file in zip format.
[marnet_densified_v2-20230619.zip](https://github.com/genthalili/searoute-py/files/11785324/marnet_densified_v2-20230619.zip)

**Comment by genthalili** [comment]
Updated in `v1.2.0`
