### ISSUE TITLE
Add Straits of Malacca to restrictions?

### ISSUE THREAD

**Issue by mildinhall** [genthalili/searoute-py#24]
Hello, have found this package very useful. I was wondering why the Straits of Malacca is not a potential restriction? 25% of the world's oil goes through there eastwards, and it's quite a bit narrower than some of the other restrictions (e.g. Gibraltar). Would it be possible to add this please?

**Comment by genthalili** [comment]
Hi @mildinhall , it seems I missed this detail.

Could you please examine and list the main water passages? Afterward, I'll perform a bulk update for the next version. Since this isn't for navigation, focus on the ones significantly affecting duration and distance.

**Comment by genthalili** [comment]
Covered in Release `1.3.1` 🚀
