### ISSUE TITLE
possibility to restrict Sunda straits?

### ISSUE THREAD

**Issue by LeoPaoli** [genthalili/searoute-py#25]
Hello, 

First of all, thank you so much for maintaining this package, it is super useful. 

I am plotting various routes across countries, and I notices that when trying to link the DRC to China, the chosen route is different to what ships normally choose. As you can see from the picture below, the route linking South Africa to China passes through the Sunda straits ( near Jakarta ). However, this route is not commonly used since that's a straight that is very difficult to navigate for large vessels, which normally pass through the Malacca straits when travelling to South Africa. 

Is there any chance you could add this straight as one of those straights that can be restricted? If not, is there any technique you could suggest I use to manually remove that passage? 

Thank you
Leonardo

![image](https://github.com/genthalili/searoute-py/assets/26929547/b6faaa33-0577-4bd7-a571-865a2a262221)

**Comment by genthalili** [comment]
Hi @LeoPaoli,

It looks similar to the previous request/issue.

I'll look up for main straits out there that are missing in the current version, then will include in the network.

If you have a list of straits, feel free to share here.

Regards

**Comment by genthalili** [comment]
Covered in Release `1.3.1` 🚀

**Comment by LeoPaoli** [comment]
Hello,
Thanks a lot!

You probably already covered it, but I would say that the list of straits
in the PDF attached is an exhaustive one.

Best
Leo
