### ISSUE TITLE
Incorrect routes with restrictions on babalmandab

### ISSUE THREAD

**Issue by Niloufar375** [genthalili/searoute-py#32]
``Hello, 
As you know with the current situation of the red sea crisis, most of the vessels are passing through the cape of good hope instead of taking the babalmandab region . My problem is concerning routes for  origin/destination ports such as Singapore and Jeddah , where the vessels are passing through the cape of good hope then suez canal to meet the port call Jeddah. However, with the current argument in the route calculation function the restriction for 'babalmandab' does not seem to have any effect as I still get the route that passes through this region ( babalmandab ) . 

`route = sr.searoute(origin, destination,restrictions=['babalmandab'])`

![Screenshot 2024-04-30 173349](https://github.com/genthalili/searoute-py/assets/127506795/2eaae1fc-d86a-432a-9627-bfcd0a4b0626)

**Comment by genthalili** [comment]
Hi @Niloufar375,
This was obviously a bug in the marnet network which had a hidden connected line on top of "babalmandab" passage, now it's fixed and will be visible in version `1.4.0` from pypi.

Meanwhile you can use this commit https://github.com/genthalili/searoute-py/commit/4dce9f57ea435a3ca2beefe7e3249b02496d011e

<img width="581" alt="image" src="https://github.com/genthalili/searoute-py/assets/3913876/ddbfee32-f5c9-40b3-98e0-0081c20b64f0">


Thanks for reporting this!

**Comment by Niloufar375** [comment]
Hey @genthalili !

Thanks for making the change , can I ask if you have a rough idea of when you will release the new version ?

**Comment by genthalili** [comment]
it should be ready during coming days, latest next week.

there is a need to test some new functionalities as some important changes have been made, also feel free to test at your end for your specific case.
