### ISSUE TITLE
Improve resolution

### ISSUE THREAD

**Issue by cerebrius** [genthalili/searoute-py#37]
Hi, is it possible to significantly increase the resolution? I tested Kiel -> Gothenburg or Stockholm -> Helsinki.

**Comment by genthalili** [comment]
Hi @cerebrius, just fixed in the latest commit (see the tag above).
Today I released latest version `1.4.1`, let's wait some days before the future release version `1.4.2` which should include this fix, meanwhile you can use the latest commit.
