### ISSUE TITLE
Routes between US West coast and Asia are plotted incorrectly

### ISSUE THREAD

**Issue by tula-geo** [genthalili/searoute-py#5]
Hi @genthalili thank you for this great package!

I seem to have a problem plotting routes between the West coast of the US and Asia though...
Is this something I am doing wrong or is it a know bug?

![image](https://user-images.githubusercontent.com/118996185/203825636-908811ff-7229-45a2-8ffb-9c05cf8140d0.png)

Many thanks!

**Comment by tula-geo** [comment]
@genthalili Thanks for your quick response!

Here the latitudes and longitudes of some examples that went wrong:
- Vancouver (49.28497584, -123.1500095) - Tokyo (35.72637966, 139. 6488745)	
- Singapore (3.2777619, 104.0787642) - San Francisco (37.81212876, -122.3139684)
- Shanghai (31.2, 121.8) - Los Angeles (33.7, -118.3)

**Comment by genthalili** [comment]
@tula-geo Which version are you using?
I tried your examples above, and they all look good to me ( also you need to set [long, lat] for origin and destination inputs) :

![image](https://user-images.githubusercontent.com/3913876/203832181-30278e93-0782-432a-947a-6f2e1111cb3a.png)
![image](https://user-images.githubusercontent.com/3913876/203832209-ff82efcb-4174-4652-af23-3359150545c9.png)
![image](https://user-images.githubusercontent.com/3913876/203832243-13b74f54-cde8-4667-888e-6511a7fc8049.png)

You should update to the latest version `1.0.8`

**Comment by tula-geo** [comment]
@genthalili Ha, you were right, I had not specified a version when installing the package and was apparently on 1.0.6.
This looks much better:

![image](https://user-images.githubusercontent.com/118996185/203835616-37c9332f-284b-4e86-8d26-eae544d633d9.png)

Thanks a lot - great stuff!

**Comment by genthalili** [comment]
@tula-geo great to hear that :)

then I'm closing this issue!
