### ISSUE TITLE
Open ocean movement can be very non-optimal

### ISSUE THREAD

**Issue by bryantek** [genthalili/searoute-py#8]
When computing routes over large sections of open ocean (particularly when approaching the origin or destination), the waypoints are sometimes chosen very non optimally. E.g. taking a spiral into the destination, or passing beyond the destination and coming back, or other right angles when cutting the corner is clearly a faster choice.
Some example origin/destination pairs that produce this:
Gulf of Mexico to Atlantic Ocean: origin = [-93.62078577368268,25.737539051869824], destination = [-40.32618417902073,6.608564614815155] (takes an inefficient route to Atlantic destination)
Gulf of Mexico to Gulf of Mexico: origin = [-91,26], destination = [-86.6796,25.3802] (should be a straight line but goes up to US coast first)

**Comment by genthalili** [comment]
hi @bryantek, thanks for using the package and reporting the issue you faced.
I think it's connected to the marine network which can be improved, especially edges in the zone of Gulf of Mexico.
I'll try to work on this for the next realse v 1.0.10

Also make sure to use the latest version of the package.

**Comment by genthalili** [comment]
Covered in version 1.1.0, please check it and let me know.

**Comment by genthalili** [comment]
Fixed as much as possible without affecting the rest of the network: 
![image](https://github.com/genthalili/searoute-py/assets/3913876/d126c42d-1c28-42fa-9d40-44f7df9b6c79)
![image](https://github.com/genthalili/searoute-py/assets/3913876/dea98a4c-e1f0-4c7e-9e03-861f151d8e34)
